export const SET_DATA = 'auth/SET_DATA'
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'

export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS'

export const VERIFY_REQUEST = 'auth/VERIFY_REQUEST'
export const VERIFY_SUCCESS = 'auth/VERIFY_SUCCESS'

export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS'

export const RESET_PASSWORD_REQUEST = 'auth/RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'auth/RESET_PASSWORD_SUCCESS'

export const HANDLE_ERROR = 'auth/HANDLE_ERROR'
